<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- AssemblyCommonInfo.cs -->
  <PropertyGroup>
    <AssemblyVersion>10.0.1</AssemblyVersion>
    <Company>CaseMaxSolutions</Company>
    <Copyright>Copyright 1999-2025 © CaseMaxSolutions</Copyright>
    <FileVersion>10.0.1.669</FileVersion>
    <InformationalVersion>10.0.1</InformationalVersion>
    <Product>IdentityServer4 10.0.0</Product>
    <PackageVersion>10.0.1</PackageVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!-- used in PackageReference[@Version] for Solutions in this repository that put nupkg files in the ./.build/packages directory -->
    <SolutionVersion>10.0.1</SolutionVersion>
  </PropertyGroup>
</Project>