<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- AssemblyCommonInfo.cs -->
  <PropertyGroup>
    <AssemblyVersion>8.0.12</AssemblyVersion>
    <Company>CaseMaxSolutions</Company>
    <Copyright>Copyright 1999-2026 © CaseMaxSolutions</Copyright>
    <FileVersion>8.0.12.26</FileVersion>
    <InformationalVersion>8.0.12</InformationalVersion>
    <Product>IdentityServer4 8.0.0</Product>
    <PackageVersion>8.0.12</PackageVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!-- used in PackageReference[@Version] for Solutions in this repository that put nupkg files in the ./.build/packages directory -->
    <SolutionVersion>8.0.12</SolutionVersion>
  </PropertyGroup>
</Project>