<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- AssemblyCommonInfo.cs -->
  <PropertyGroup>
    <AssemblyVersion>6.0.16</AssemblyVersion>
    <Company>CaseMaxSolutions</Company>
    <Copyright>Copyright 1999-2026 © CaseMaxSolutions</Copyright>
    <FileVersion>6.0.16.2</FileVersion>
    <InformationalVersion>6.0.16</InformationalVersion>
    <Product>IdentityServer4 6.0.0</Product>
    <PackageVersion>6.0.16</PackageVersion>
  </PropertyGroup>
  <PropertyGroup>
    <!-- used in PackageReference[@Version] for Solutions in this repository that put nupkg files in the ./.build/packages directory -->
    <SolutionVersion>6.0.16</SolutionVersion>
  </PropertyGroup>
</Project>