<#
.SYNOPSIS
Calls git merge with the Branch if there are changes that need
to be merged.  The changeset generated by the merge is NOT 
committed yet.

.DESCRIPTION
Merges the content of the Branch into the local working directory for 
the HEAD

.PARAMETER Branch
The name of the branch that should be merged into the checked out branch.  This
will default to the value in merge-branch.txt if none is specified.

.PARAMETER Local
A flag indicating if the local branch should be used instead of the 
origin remote.

#>
param(
    [string]
    $Branch = '',

    [switch]
    $Local
)

# change the git.exe output it sends to STDERR to go to STDOUT so that the 
# progress reports or additional info that git.exe writes to STDERR are not
# considered an error by cc.net
$env:GIT_REDIRECT_STDERR = '2>&1'

if ($Branch -eq '') {
    $Branch = (Get-Content -Path '.\merge-branch.txt')
}

$head = $(git.exe symbolic-ref --short HEAD)

$rev = "origin/$Branch"
if ($Local -eq $true){
    $rev = "$Branch"
}

Write-Host "getting log of changes from $rev that need to be merged into $head"

$logOutput = $(git.exe log HEAD..$rev)
 
if (!$logOutput) {
    Write-Host "nothing to merge into $head from $rev"
}
else {
    Write-Host "merging $head with $rev"
    git.exe merge --no-commit $rev
}
